<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');
/**
 * Name:  Auth Lang - English
 *
 * Author: Ben Edmunds
 * 		  ben.edmunds@gmail.com
 *         @benedmunds
 *
 * Author: Daniel Davis
 *         @ourmaninjapan
 *
 * Location: http://github.com/benedmunds/ion_auth/
 *
 * Created:  03.09.2013
 *
 * Description:  English language file for Ion Auth example views
 *
 */
// Errors
$lang['error_csrf'] = 'This form post did not pass our security checks.';



$lang['name'] = 'Name';
$lang['facebook'] = 'facebook';
$lang['tpa_manage'] = 'TPA Management';
$lang['tax_c'] = 'TAX';
$lang['sub_c'] = 'SUB TOTAL';
$lang['note_c'] = 'NOTICE';
$lang['grand_c'] = 'GRAND TOTAL';
$lang['go_back'] = 'Go Back';
$lang['mail_supp'] = 'Mail PO to Supplier';
$lang['download'] = 'Download';
$lang['count'] = 'Count';
$lang['mark_paid'] = 'Mark Purchase Order as Paid and Completed';
$lang['pdf'] = 'Pdf';
$lang['po_den_by'] = 'PO Generated by';
$lang['auto_gen'] = 'Auto Generated';
$lang['send_sms'] = 'Send SMS';
$lang['view_all_po'] = 'View All PO';
$lang['create'] = 'Create';
$lang['patient_sales'] = 'Patient and Sales';
$lang['c_date'] = 'Closing Date';
$lang['submitted'] = 'Submitted';
$lang['closed'] = 'Closed';
$lang['received'] = 'Received';
$lang['quote'] = 'Quote';
$lang['request'] = 'Request';
$lang['sender'] = 'Sender';
$lang['beds'] = 'Beds';
$lang['assign'] = 'Assign';
$lang['create_bed'] = 'Create Bed';
$lang['api_id'] = 'API ID';
$lang['clickatell'] = 'Clickatell';
$lang['username'] = 'Username';
$lang['and'] = 'and';
$lang['new'] = 'New';
$lang['ex_status'] = 'Expiry Status';
$lang['message'] = 'Message';
$lang['fromm'] = 'From';
$lang['delivery'] = 'Delivery';
$lang['sent'] = 'Sent';
$lang['to_blog'] = 'To Blog';
$lang['transfer'] = 'Transfer';
$lang['emanating_blog'] = 'Emanating Blog';
$lang['delivery_date'] = 'Delivered Date';
$lang['financial_activity'] = 'Sales Activity';
$lang['send_wishes'] = 'Send Wishes';
$lang['amount_to_be_paid_patient'] = 'Amount Due by Patient';
$lang['sales_graph'] = 'Sales Graph';
$lang['expense_graph'] = 'Expenses Graph';
$lang['banned_supplier'] = 'Frozen Supplier';
$lang['this_month_sale_expense_pie_chart'] = 'Sale - Expense Pie Chart';
$lang['unban_supplier'] = 'Unfreeze Supplier';
$lang['banned'] = 'Frozen';
$lang['calander'] = 'Calender';
$lang['tax'] = 'Tax';
$lang['total'] = 'Total';
$lang['order_date'] = 'Order Date';
$lang['order_due_date'] = 'Order Due Date';
$lang['payment'] = 'Payment';
$lang['ban'] = 'Freeze';
$lang['view_po'] = 'View Purchase Order';
$lang['terms'] = 'Terms';
$lang['number'] = 'number';
$lang['view'] = 'View';
$lang['payment_history'] = 'Payment History';
$lang['prospective'] = 'Prospective';
$lang['activate_supplier'] = 'Activate Supplier';
$lang['done_orders'] = 'Done Orders';
$lang['paid_orders'] = 'Paid Orders';
$lang['search_po_with'] = 'Search PO by ID';
$lang['delivered_orders'] = 'Delivered Orders';
$lang['cancelled_orders'] = 'Cancelled Orders';
$lang['cancel_date'] = 'Cancelled Date';
$lang['language'] = 'Language';
$lang['french'] = 'French';
$lang['delivered_date'] = 'Delivered Date';
$lang['appointment_calander'] = 'Appointment Calender';
$lang['mark_po_as_delivered'] = 'mark PO as Delivered';
$lang['mark_as_delivered'] = 'Mark as Received';
$lang['purchase_product'] = 'Purchased Product';
$lang['purchased_amount'] = 'Purchased Amount';
$lang['payment_status'] = 'Payment Status';
$lang['my'] = 'My';
$lang['v_number'] = 'Vehicle Number';
$lang['v_model'] = 'Vehicle Model';
$lang['year_made'] = 'Year Made';
$lang['driver_n'] = 'Driver Name';
$lang['tpa'] = 'TPA';
$lang['register'] = 'Register';
$lang['driver_c'] = 'Driver Contact';
$lang['driver_l'] = 'Driver License';
$lang['v_type'] = 'Vehicle Type';
$lang['todays'] = 'Todays';
$lang['note'] = 'Note';
$lang['calls'] = 'Calls';
$lang['call'] = 'Call';
$lang['upcoming'] = 'Upcoming';
$lang['pending'] = 'Pending';
$lang['confirmed'] = 'Confirmed';
$lang['confirm'] = 'Confirm';
$lang['time'] = 'Time';
$lang['approve'] = 'Approve';
$lang['approved'] = 'Approved';
$lang['cancel_po'] = 'Cancel PO';
$lang['cancelled'] = 'Cancelled';
$lang['english'] = 'English';
$lang['spanish'] = 'Spanish';
$lang['payment'] = 'Payment';
$lang['options'] = 'Action';
$lang['date-time'] = 'Date';
$lang['description'] = 'Description';
$lang['login'] = 'Login';
$lang['forgot_password'] = 'Forgot Password?';
$lang['password'] = 'Password';
$lang['sign_in'] = 'sign In';
$lang['useremail'] = 'User Email';
$lang['reset_message'] = '';
$lang['email'] = 'Email';
$lang['cancel'] = 'Cancel';
$lang['dashboard'] = 'Information Panel';
$lang['expense'] = 'Expense';
$lang['total_payment'] = 'Total payment';
$lang['settings'] = 'Settings';
$lang['profile'] = 'Profile';
$lang['my_profile'] = 'My Profile';
$lang['my_consultant'] = 'My Consultant';
$lang['my_due_balance'] = 'My Due Balance';
$lang['my_last_login'] = 'My Last Login';
$lang['my_reports'] = 'My Reports';
$lang['lms'] = 'Livestock Management System'; 
$lang['payment_today'] = 'Payment Today';
$lang['payments_today'] = 'Payments Today';
$lang['log_out'] = 'Log Out';



$lang['due_balance'] = 'Due Balance';
$lang['invoice'] = 'Invoice';
$lang['details'] = 'Details';
$lang['bio_graph'] = 'Bio Graph';
$lang['gender'] = 'Gender';


// Finance
$lang['payments'] = 'Payments';
$lang['date'] = 'Date';
$lang['sub_total'] = 'Sub Total';
$lang['discount'] = 'Discount';
$lang['vat'] = 'Vat';
$lang['total'] = 'Total';
$lang['status'] = 'Status';
$lang['invoice_info'] = 'INVOICE INFO';
$lang['invoice_status'] = 'INVOICE STATUS';
$lang['paid'] = 'Paid';

$lang['add_payment'] = 'Add Payment';
$lang['edit_payment'] = 'Edit Payment';
$lang['payment_categories'] = 'Payment Categories';
$lang['edit_payment_category'] = 'Edit Payment Category';
$lang['amount'] = 'Amount';
$lang['submit'] = 'Submit';
$lang['add_more_categories'] = 'Add More Categories';
$lang['category'] = 'Category';
$lang['expenses'] = 'Expenses';
$lang['add_expense'] = 'Add Expense';
$lang['edit_expense'] = 'Edit Expense';
$lang['expense_category'] = 'Expense categories';
$lang['add_expense_category'] = 'Add Expense Category';
$lang['edit_expense_category'] = 'Edit Expense Category';
$lang['financial_report'] = 'Financial Report';
$lang['payment_report'] = 'Payment Report';
$lang['expense_report'] = 'Expense Report';
$lang['gross_payment'] = 'Gross Payment';
$lang['gross_expense'] = 'Gross Expense';
$lang['total'] = 'Total';
$lang['sub_total'] = 'Sub Total';
$lang['profit'] = 'Profit';
$lang['payment_to'] = 'PAYMENT TO';
$lang['bill_to'] = 'BILL TO';
$lang['invoice_number'] = 'Invoice No.';
$lang['invoice'] = 'Invoice';
$lang['grand_total'] = 'Grand Total';
$lang['make_paid'] = 'Make Paid';
$lang['edit_invoice'] = 'Edit Invoice';
$lang['percentage'] = 'Percentage';
$lang['flat'] = 'Flat';
$lang['from'] = 'From:';
$lang['to'] = 'To:';
$lang['all_total_due'] = 'All Total Due';
$lang['quantity'] = 'Quantity';
$lang['sex'] = 'Sex';
$lang['male'] = 'Male';
$lang['female'] = 'Female';


//Settings
$lang['system_name'] = 'System Name';
$lang['title'] = 'Title';
$lang['address'] = 'Address';
$lang['phone'] = 'Phone';
$lang['currency'] = 'Currency';
$lang['discount_type'] = 'Discount Type';

//Profile
$lang['change_password'] = 'Change Password';
$lang['manage_profile'] = 'Manage Profile';

//options button
$lang['edit'] = 'Edit';
$lang['info'] = 'Info';
$lang['delete'] = 'Delete';


$lang['welcome_short'] =  'Welcome Short';
$lang['welcome_long'] =  'Welcome Long';
$lang['leave'] =  'Leave';
$lang['leave_app'] =  'Leave Application';
$lang['leave_apply'] =  'Apply Leave';
$lang['pharmacy'] =  'Pharmacy';
$lang['MedicineCategory'] =  'Medicine Category';
$lang['soon_expire'] =  'Soon Expire';
$lang['gross_total'] =  'Gross Total';
$lang['amount_received'] =  'Amount Received';
$lang['gross_expense'] = 'Gross Expense';
$lang['total'] = 'Total';
$lang['sub_total'] = 'Sub Total';
$lang['due_amount'] = 'Due Amount';
$lang['due_balance'] = 'Due Balance';
$lang['unpaid'] = 'Unpaid';
$lang['paid_partially'] = 'Paid Partially';
$lang['paid'] = 'Paid';
$lang['amount_to_be_paid'] = 'Amount To Be Paid';
$lang['amount_received'] = 'Amount Received';

// dashboard
$lang['login'] = 'Login';
$lang['forgot_password'] = 'Forgot Password?';
$lang['sign_in'] = 'sign In';
$lang['useremail'] = 'User Email';
$lang['reset_message'] = '';
$lang['email'] = 'Email';
$lang['cancel'] = 'Cancel';
$lang['hospital'] = 'Hospital';


$lang['dashboard'] = 'Information Panel';

$lang['supplier'] = 'Supplier';
$lang['paid'] = 'Paid';
$lang['code'] = 'Code';
$lang['contact_name'] = 'Contact name';
$lang['contact_phone'] = 'Contact phone';
$lang['status'] = 'Status';
$lang['blog'] = 'Blog';
$lang['staff'] = 'Staff';
$lang['pharmacist'] = 'Pharmacist';
$lang['pharmacists'] = 'Pharmacists';
$lang['nurse'] = 'Nurse';
$lang['nurses'] = 'Nurses';
$lang['medical_history'] = 'Medical History';
$lang['img'] = 'IMG';
$lang['laboratorist'] = 'Laboratorist';
$lang['laboratorists'] = 'Laboratorists';
$lang['accountant'] = 'Accountant';
$lang['accountants'] = 'Accountants';
$lang['receptionist'] = 'Receptionist';
$lang['receptionists'] = 'Receptionists';
$lang['payment'] = 'Payment';
$lang['medicine'] = 'Medicine';
$lang['report'] = 'Report';
$lang['reports'] = 'Reports';
$lang['total_payment'] = 'Total payment';
$lang['departments'] = 'Departments';
$lang['human_resources'] = 'Human Resources';
$lang['financial_activities'] = 'Financial Activities';
$lang['settings'] = 'Settings';
$lang['profile'] = 'Profile';
$lang['my'] = 'My';
$lang['addmission'] = 'Admission';
$lang['case_hx'] = 'Case History';
$lang['exam_findings'] = 'Examination Findings';
$lang['clear_due_amount'] = 'Clear Due Payment';
$lang['days'] = 'Days';
$lang['diagnosis'] = 'Diagnosis';
$lang['zoom'] = 'Zoom';
$lang['go_live'] = 'Go Live';
$lang['meetings'] = 'Meetings';
$lang['live'] = 'Live';
$lang['archived'] = 'Archived';
$lang['fromm'] = 'From';
$lang['requests'] = 'Requests';
$lang['medical_hx'] = 'Medical History';
$lang['add_document'] = 'Add Document';
$lang['admit_hx'] = 'Admission History';
$lang['appoint_hx'] = 'Appointment History';
$lang['pay_hx'] = 'Payment History';
$lang['due_payment'] = 'Due Payment';
$lang['admission_details'] = 'Admission Details';
$lang['my_profile'] = 'My Profile';
$lang['my_consultant'] = 'My Consultant';
$lang['my_due_balance'] = 'My Due Balance';
$lang['my_last_login'] = 'My Last Login';
$lang['my_reports'] = 'My Reports';
$lang['general_settings'] = 'General Settings';
$lang['Manage_profile'] = 'Manage Profile';
$lang['change_pass'] = 'Change Password';
$lang['sales'] = 'Sales';
$lang['add_sales'] = 'Add Sales';
$lang['finance'] = 'Finance';
$lang['declined'] = 'Declined';
$lang['decline'] = 'Decline';
$lang['admit'] = 'Admit';
$lang['insurance'] = 'Insurance';
$lang['policy_no'] = 'Policy Number';
$lang['price'] = 'Price';
$lang['full_name'] = 'Full Names';
$lang['admit_count'] = 'Admission Count';
$lang['doc_com'] = 'Doctors Commission';
$lang['paymentProcedures'] = 'Payment Procedures';


$lang['see_all_blogs'] = 'See All Blogs'; 
$lang['see_all_payments'] = 'See All Payments';
$lang['see_all_medicines'] = 'See All Medicine';
$lang['payment_today'] = 'Payment Today';
$lang['payments_today'] = 'Payments Today';

$lang['log_out'] = 'Log Out';





//sidebar
$lang['dashboard'] = 'Home';



// Departments
$lang['name'] = 'Name';
$lang['description'] = 'Description';
$lang['options'] = 'Actions';
$lang['print'] = 'Print';


// Supplier
$lang['suppliers'] = 'Suppliers';
$lang['patient'] = 'Patient';
$lang['patients_due'] = 'Patient with Debt';
$lang['patients'] = 'Patients';
$lang['list_of_suppliers'] = 'List of Suppliers';
$lang['list_of_patients'] = 'List of Patients';
$lang['add_suppliers'] = 'Add Suppliers';
$lang['add_patients'] = 'Add Patients';
$lang['add_supplier'] = 'Add Supplier';
$lang['edit_suppliers'] = 'Edit Suppliers';
$lang['edit_supplier'] = 'Edit Supplier';
$lang['image'] = 'Image';
$lang['email'] = 'Email';
$lang['address'] = 'Address';
$lang['phone'] = 'Phone';
$lang['password'] = 'Password';
$lang['supplier_id'] = 'ID';

// Blog
$lang['add_blog'] = 'Add Blog';
$lang['all_blogs'] = 'Blogs';
$lang['register_new_blog'] = 'Add Blog';
$lang['blog_registration'] = 'Add Blog';
$lang['edit_blog'] = 'Edit Blog';
$lang['all_quantity'] = 'Quantity';
$lang['all_products'] = 'Items';
$lang['invoice'] = 'Invoice';
$lang['details'] = 'Details';
$lang['bio_graph'] = 'Bio Graph';
$lang['blog_id'] = 'ID';

$lang['all_items'] = 'Items';
$lang['item'] = 'Item';
$lang['add_item'] = 'Add Item';
$lang['edit_item'] = 'Edit Item';
$lang['view_item'] = 'View Item';
$lang['close'] = 'Close';

$lang['qty'] = 'Quantity';
$lang['qty_type'] = 'Quantity Types';
$lang['Net_price'] = 'Net Price';
$lang['qty_typ'] = 'Quantity Type';
$lang['add_qty_type'] = 'Add Quantity Type';
$lang['edit_qty_type'] = 'Edit Quantity Types';


$lang['about_us'] = 'About Us';
$lang['department'] = 'Department';
$lang['bloodbank'] = 'Blood Bank';
$lang['b_group'] = 'Blood Group';
$lang['donate_date'] = 'Donation Date';
$lang['last_donate_date'] = 'Last Donation Date';
$lang['others'] = 'Others';
$lang['donor'] = 'Donor';
$lang['post'] = 'Post';
$lang['posts'] = 'Posts';
$lang['bed'] = 'Bed';
$lang['website'] = 'website';
$lang['allot'] = 'Allot';
$lang['types'] = 'Types';
$lang['from_date'] = 'From Date';
$lang['to_date'] = 'To Date';
$lang['admin'] = 'Admin';
$lang['birth'] = 'Birth';
$lang['death'] = 'Death';
$lang['surgery'] = 'Surgery';
$lang['profile_that_can_see'] = 'Profiles that can see this notice';
$lang['select'] = 'Select';
$lang['cause_of_death'] = 'Cause of Death';
$lang['doctor'] = 'Doctor';
$lang['doctors'] = 'Doctors';
$lang['operation'] = 'Operation';
$lang['alloted'] = 'Alloted';
$lang['financial'] = 'Financial';
$lang['available'] = 'Available';
$lang['ambulance'] = 'Ambulance';
$lang['appointment'] = 'Appointment';
$lang['human_res'] = 'Human Resource';
$lang['number_per_page'] = 'Number of Posts Per Page';
$lang['number_per_other_post'] = 'Number of Other Posts Per Page';




// Purchase Order
$lang['purchase_orders'] = 'Purchase Orders';
$lang['generate_order'] = 'Generate Order';
$lang['purchase_order'] = 'Purchase Order';
$lang['due_date'] = 'Due Date';
$lang['delivery_due_date'] = 'Delivery Due Date';
$lang['update_order'] = 'Update Order';
$lang['tot_amount'] = 'Total Amount';
$lang['change_status'] = 'Change Status';
$lang['po'] = 'Purchase Order';
$lang['pos'] = 'Purchase Orders';
$lang['id'] = 'ID';
$lang['date-time'] = 'Date - Time';
$lang['remarks'] = 'Remarks';
$lang['add_po'] = 'Add Purchase Order';
$lang['edit_po'] = 'Edit Purchase Order';
$lang['start_time'] = 'Start Time';
$lang['end_time'] = 'End Time';


// Staff
$lang['add_staff'] = 'Add Staff';
$lang['staffs'] = 'Staffs';
$lang['edit_staff'] = 'Edit Staff';

//Settings
$lang['system_name'] = 'System Name';
$lang['title'] = 'Title';
$lang['address'] = 'Address';
$lang['phone'] = 'Phone';
$lang['hospital_email'] = 'Hospital Email';
$lang['currency'] = 'Currency';
$lang['discount_type'] = 'Discount Type';

//Profile
$lang['change_password'] = 'Change Password';
$lang['manage_profile'] = 'Manage Profile';
$lang['role_permission'] = 'Role Permission';
$lang['staff_permission'] = 'Staff Permission';
$lang['products'] = 'Products';
$lang['product'] = 'Product';
$lang['all_product'] = 'All Products';
$lang['out_of_stock'] = 'Out of Stock';

//options button

$lang['edit'] = 'Edit';
$lang['info'] = 'Info';
$lang['blog_items'] = 'Blog Items';
$lang['delete'] = 'Delete';
$lang['history'] = 'History';
$lang['module_permission'] = 'Staff Permission';
$lang['permission'] = 'Permission';
$lang['no_permission'] = 'Access Denied';


$lang['accounting'] = 'Account';
$lang['human_resource'] = 'Human Resource';
$lang['add_category_stock'] = 'Add Category Stock';
$lang['edit_category_stock'] = 'Edit Category Stock';
$lang['category'] = 'Category';
$lang['stock'] = 'Stock';
$lang['add'] = 'Add';
$lang['stock_in_category'] = 'Stock in Category';
$lang['list_stock'] = 'List Stock';
$lang['all_stock'] = 'All Stock';
$lang['add_stock'] = 'Add Stock';
$lang['qr_code'] = 'QR Code';
$lang['patients'] = 'Patients';
$lang['list'] = 'List';
$lang['with_due'] = 'with Due';
$lang['inventory'] = 'Inventory';
$lang['expired'] = 'Expired';
$lang['out'] = 'Out';
$lang['sms'] = 'SMS';
$lang['send'] = 'Send';
$lang['stock_for'] = 'Stock in';
$lang['qtyy'] = 'Qty';
$lang['str_box'] = 'Store Box';
$lang['cost'] = 'Unit Cost Price';
$lang['sale'] = 'Unit Sale Price';
$lang['ex_date'] = 'Expiry Date';
$lang['sale'] = 'Unit Sale Price';
$lang['in'] = 'in';
$lang['logo'] = 'Logo';
$lang['favicon'] = 'Favicon';
$lang['access_is_denied'] = 'Access Denied';
$lang['access_deny_message'] = 'you do not have the permission to view this page';
$lang['on'] = 'On';
$lang['off'] = 'Off';
$lang['all'] = 'All';
$lang['out_of'] = 'Out of';
$lang['latest'] = 'Latest';
$lang['expiration'] = 'Expiration';
$lang['notice'] = 'Notice';
$lang['expirable_product'] = 'Expirable Product';
$lang['role'] = 'Role';
$lang['dob'] = 'Date Of Birth';
$lang['birthday'] = 'Birthday';
$lang['wishes'] = 'Wishes';
$lang['today'] = 'Today';
$lang['home'] = 'Home';
$lang['age'] = 'Age';
$lang['PO'] = 'PO';
$lang['prefix'] = 'Prefix';
$lang['patient_bday'] = 'Patient Birthday';
$lang['company_key'] = 'Company Key';
$lang['payment_mode'] = 'Payment Method';
$lang['supplier_request'] = 'Prospective';
$lang['supplier_requests'] = 'Prospective Supplier';




$lang['tn_num'] = 'Tax ID';
$lang['city'] = 'City';
$lang['sort_code'] = 'Sort Code';
$lang['account_name'] = 'Account Name';
$lang['account_number'] = 'Account Number';
$lang['postal_code'] = 'Postal Code';
$lang['state'] = 'State';
$lang['country'] = 'Country';
$lang['unit'] = 'Unit';
$lang['fee'] = 'Fee';
$lang['type'] = 'Type';
$lang['alloted'] = 'Alloted';
$lang['discharge'] = 'Discharge';
$lang['assign'] = 'Assign';
$lang['Account Information'] = 'Account Information';



$lang['bank_name'] = 'Bank Name';
$lang['quotes'] = 'Bed';
$lang['submit'] = 'Submit';
$lang['y_est'] = 'Year Established';
$lang['company'] = 'Company Name';
$lang['rc_num'] = 'RC Number';
$lang['employ'] = 'Employee';
$lang['short'] = 'Short';
$lang['Primary_Contact'] = 'Primary Contact';
$lang['first_name'] = 'First Name';
$lang['last_name'] = 'Last Name';
$lang['po_email'] = 'PO & Quote Email';
$lang['general_information'] = 'General Information';



$lang['system_title'] = 'Supplier';
$lang['gross_total'] =  'Gross Total';
$lang['amount_received'] =  'Amount Received';
$lang['gross_expense'] = 'Gross Expense';
$lang['total'] = 'Total';
$lang['sub_total'] = 'Sub Total';
$lang['due_amount'] = 'Due Amount';
$lang['due_balance'] = 'Due Balance';
$lang['blog_id'] = 'Blog ID';

$lang['unpaid'] = 'Unpaid';
$lang['my_purchase_orders'] = 'My PurchaseOrders';
